---
openapi: 3.0.0
info:
  title: world-cup-api
  description: The API for the World Cup 2022 project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/BARTUSBAZSI/WorldCupAPI/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /teams:
    get:
      tags:
      - Team
      description: returns all registered devices
      operationId: getTeams
      parameters:
      - name: skip
        in: query
        description: number of records to skip
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: max number of records to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: All the teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
components:
  schemas:
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Brazil
        rankingPoints:
          type: number
          format: double
        flagPath:
          type: string
          example: https://www.worldometers.info/img/flags/br-flag.gif
    TournamentGroup:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Brazil
        teams:
          type: array
          items:
            $ref: '#/components/schemas/Team'
        matches:
          type: array
          items:
            $ref: '#/components/schemas/Match'
    Match:
      type: object
      properties:
        id:
          type: integer
          format: int64
        startDate:
          type: string
        stadium:
          type: string
        teams:
          type: array
          items:
            $ref: '#/components/schemas/Team'
